# Generated by Django 4.2.14 on 2024-10-13 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Image', models.ImageField(unique=True, upload_to='images')),
                ('Uploaded_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['Name'],
            },
        ),
    ]
