# Generated by Django 4.2.14 on 2024-10-14 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_remove_pic_uploaded_date_pic_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pic',
            name='Image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
